### ISSUE TITLE
Could not find eventmachine-1.2.7 in any of the sources

### ISSUE THREAD

**Issue by obaqueiro** [ruby-grape/grape-on-goliath#2]
Trying to test this, after downloading I run:

`bundle install`

and then

`bundle exec ruby app.rb`

And I get:

`Could not find eventmachine-1.2.7 in any of the sources`

**Comment by dblock** [comment]
The version of eventmachine in Gemfile.lock is not 1.2.7. 

Check whether `bundle install` succeeded. Then make sure you didn't `bundle update` (that there were no files modified). It worked for me "as is".

Run `bundle exec ruby app.rb -sv` to see some output. Or `gem install foreman` and `foreman start`, which uses [Procfile](https://github.com/ruby-grape/grape-on-goliath/blob/master/Procfile).

I did update dependencies in #3.

**Comment by dblock** [comment]
I'll close this, but feel free to tack on questions and I'll try to help out.
